version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticSearchDb-container
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana-container
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
networks:
  es-net:
    driver: bridge
      
